/* ═══════════════════════════════════════════════════════
   script.js  —  Asset Allocation Dashboard
   Reads from data/allocations.json (generated by Python)
   Falls back to data/allocations_fallback.json if needed
═══════════════════════════════════════════════════════ */

const SIGNALS = { HOW:'Heavy OW', OW:'Overweight', N:'Neutral', UW:'Underweight', HUW:'Heavy UW' };
const SCORE   = { HOW:2, OW:1, N:0, UW:-1, HUW:-2 };

let dashData    = null;   // full loaded JSON
let broadChart  = null;
let histChart   = null;
let currentTab  = 'all';

/* ─────────────────────────────────────────
   BOOT — load data then render everything
───────────────────────────────────────── */
async function boot() {
  showLoading(true);
  try {
    // Try live data first, then fallback
    let data;
    try {
      const r = await fetch(`data/allocations.json?t=${Date.now()}`);
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      data = await r.json();
    } catch {
      const r2 = await fetch('data/allocations_fallback.json');
      if (!r2.ok) throw new Error('No data files found.');
      data = await r2.json();
      document.getElementById('data-source-label').textContent = '⚠ Using fallback data — run update_data.py to refresh';
    }

    dashData = data;
    renderAll(data);
    showLoading(false);
    document.getElementById('main-content').style.display = 'block';
  } catch (err) {
    showLoading(false);
    showError(err.message);
  }
}

function refreshData() { boot(); }

function showLoading(on) {
  document.getElementById('loading-state').style.display = on ? 'flex' : 'none';
  document.getElementById('error-state').style.display   = 'none';
}
function showError(msg) {
  document.getElementById('loading-state').style.display = 'none';
  document.getElementById('error-state').style.display   = 'flex';
  document.getElementById('error-msg').textContent       = '⚠ ' + msg;
}

/* ─────────────────────────────────────────
   RENDER ALL SECTIONS
───────────────────────────────────────── */
function renderAll(data) {
  document.getElementById('data-date').textContent = data.as_of || '—';
  if (!document.getElementById('data-source-label').textContent.includes('fallback')) {
    document.getElementById('data-source-label').textContent = `Q${getQuarter(data.as_of)} ${getYear(data.as_of)} tactical outlook`;
  }
  buildBroadGrid(data.broad);
  buildBroadChart(data.broad);
  buildTable(data.assets, 'all');
  buildHeatmap(data.assets);
  buildHistoryChart(data.history || [], data.assets);
}

function getQuarter(dateStr) {
  const m = new Date(dateStr).getMonth();
  return Math.floor(m / 3) + 1;
}
function getYear(dateStr) { return new Date(dateStr).getFullYear(); }

/* ─────────────────────────────────────────
   BROAD ALLOCATION CARDS
───────────────────────────────────────── */
function buildBroadGrid(broad) {
  const configs = [
    { key:'NDR',       color:'ndr', label:'Ned Davis Research' },
    { key:'BlackRock', color:'bl',  label:'BlackRock Target' },
    { key:'BCA',       color:'bca', label:'BCA Research' },
  ];
  document.getElementById('broad-grid').innerHTML = configs.map(c => {
    const d = broad[c.key] || {};
    return `
    <div class="broad-card">
      <div class="broad-card-header">
        <span class="firm-label firm-${c.color}">${c.label}</span>
        <span style="font-size:.65rem;color:var(--c-dim)">Tactical Model</span>
      </div>
      <div class="broad-bars">
        ${bar('Equity','bar-fill-equity', d.equity  || 0)}
        ${bar('Debt',  'bar-fill-debt',   d.debt    || 0)}
        ${bar('Cash',  'bar-fill-cash',   d.cash    || 0)}
      </div>
      <p class="broad-note">${d.note || ''}</p>
    </div>`;
  }).join('');
}

function bar(label, cls, pct) {
  return `
  <div class="bar-row">
    <span class="bar-row-label">${label}</span>
    <div class="bar-track"><div class="bar-fill ${cls}" style="width:${pct}%"></div></div>
    <span class="bar-pct">${pct}%</span>
  </div>`;
}

/* ─────────────────────────────────────────
   BROAD CHART (Chart.js grouped bar)
───────────────────────────────────────── */
function buildBroadChart(broad) {
  if (broadChart) broadChart.destroy();
  const firms  = ['NDR', 'BlackRock', 'BCA'];
  const labels = ['Equity', 'Debt', 'Cash'];
  const colors = { NDR:'#6c8ff5', BlackRock:'#38c8a8', BCA:'#f59e42' };

  const datasets = firms.map(f => ({
    label: f,
    data: [broad[f]?.equity || 0, broad[f]?.debt || 0, broad[f]?.cash || 0],
    backgroundColor: colors[f] + '99',
    borderColor: colors[f],
    borderWidth: 1.5,
    borderRadius: 4,
  }));

  broadChart = new Chart(document.getElementById('broadChart'), {
    type: 'bar',
    data: { labels, datasets },
    options: {
      responsive: true, maintainAspectRatio: false,
      plugins: { legend: { display: false } },
      scales: {
        x: { grid: { color: '#252a3a' }, ticks: { color: '#8892aa', font: { size: 11 } } },
        y: {
          min: 0, max: 100,
          grid: { color: '#252a3a' },
          ticks: { color: '#8892aa', font: { size: 11 }, callback: v => v + '%' }
        }
      }
    }
  });

  // Custom legend
  const leg = firms.map(f =>
    `<span style="display:flex;align-items:center;gap:5px">
      <span style="width:10px;height:10px;border-radius:2px;background:${colors[f]}"></span>
      ${f}
    </span>`
  ).join('');
  // Insert legend above chart card
  const card = document.getElementById('broadChart').closest('.chart-card');
  let legEl = card.querySelector('.chart-legend');
  if (!legEl) {
    legEl = document.createElement('div');
    legEl.className = 'chart-legend';
    legEl.style.cssText = 'display:flex;gap:16px;margin-bottom:10px;font-size:.7rem;color:var(--c-muted)';
    card.insertBefore(legEl, card.querySelector('div'));
  }
  legEl.innerHTML = leg;
}

/* ─────────────────────────────────────────
   SIGNAL HELPERS
───────────────────────────────────────── */
function sigBadge(code) {
  return `<span class="signal signal-${code}">${SIGNALS[code] || code}</span>`;
}
function momBadge(dir) {
  if (dir === 'up') return '<span class="change-badge change-up">▲ Upgraded</span>';
  if (dir === 'dn') return '<span class="change-badge change-dn">▼ Downgraded</span>';
  return '<span class="change-badge change-nc">— Unchanged</span>';
}
function signalColor(s) {
  return { HOW:'#22c55e', OW:'#4ade80', N:'#8892aa', UW:'#f87171', HUW:'#ef4444' }[s] || '#8892aa';
}
function consensusBadge(ndr, bl, bca) {
  const scores = [SCORE[ndr]||0, SCORE[bl]||0, SCORE[bca]||0];
  const avg    = scores.reduce((a,b)=>a+b,0) / 3;
  let cls;
  if      (avg >= 1.5)  cls = 'HOW';
  else if (avg >= 0.5)  cls = 'OW';
  else if (avg >= -0.5) cls = 'N';
  else if (avg >= -1.5) cls = 'UW';
  else                  cls = 'HUW';

  const bars = [ndr,bl,bca].map((s,i) => {
    const h = 6 + Math.abs(SCORE[s]||0) * 4;
    return `<div class="bc" style="background:${signalColor(s)};height:${h}px"
      title="${['NDR','BlackRock','BCA'][i]}: ${SIGNALS[s]}"></div>`;
  }).join('');

  return `<div class="consensus-cell">
    <div class="bar-consensus">${bars}</div>
    <span class="signal signal-${cls}" style="font-size:.63rem;padding:2px 8px;min-width:76px">${SIGNALS[cls]}</span>
  </div>`;
}
function momComposite(a) {
  const vals = [a.momNDR, a.momBL, a.momBCA];
  const ups  = vals.filter(v=>v==='up').length;
  const dns  = vals.filter(v=>v==='dn').length;
  return momBadge(ups>dns ? 'up' : dns>ups ? 'dn' : 'nc');
}

/* ─────────────────────────────────────────
   MAIN TABLE
───────────────────────────────────────── */
function setTab(tab, el) {
  currentTab = tab;
  document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
  el.classList.add('active');
  buildTable(dashData?.assets || [], tab);
}

function buildTable(assets, tab) {
  const filtered = tab === 'all' ? assets : assets.filter(a => a.cat === tab);
  let currentGroup = '';
  let html = '';
  filtered.forEach(a => {
    if (a.group !== currentGroup) {
      currentGroup = a.group;
      html += `<tr class="group-header"><td colspan="6">${a.group}</td></tr>`;
    }
    html += `<tr>
      <td>
        <div class="asset-name" data-tip="${a.note || ''}">${a.name}</div>
        <div class="asset-sub">${a.sub || ''}</div>
      </td>
      <td class="center">${sigBadge(a.NDR)}</td>
      <td class="center">${sigBadge(a.BlackRock)}</td>
      <td class="center">${sigBadge(a.BCA)}</td>
      <td class="center">${consensusBadge(a.NDR, a.BlackRock, a.BCA)}</td>
      <td class="center">${momComposite(a)}</td>
    </tr>`;
  });
  document.getElementById('table-body').innerHTML = html;
}

/* ─────────────────────────────────────────
   HEATMAP
───────────────────────────────────────── */
function buildHeatmap(assets) {
  const hm = document.getElementById('heatmap');
  const hdrs = [
    `<div class="hm-header" style="background:transparent;color:var(--c-dim);text-align:left;font-size:.65rem">Asset Class</div>`,
    `<div class="hm-header" style="background:rgba(108,143,245,.1);color:var(--c-ndr)">NDR</div>`,
    `<div class="hm-header" style="background:rgba(56,200,168,.1);color:var(--c-bl)">BlackRock</div>`,
    `<div class="hm-header" style="background:rgba(245,158,66,.1);color:var(--c-bca)">BCA</div>`,
  ].join('');
  const rows = assets.map(a => [
    `<div class="hm-label">${a.name}</div>`,
    `<div class="hm-cell hm-${a.NDR}">${SIGNALS[a.NDR]}</div>`,
    `<div class="hm-cell hm-${a.BlackRock}">${SIGNALS[a.BlackRock]}</div>`,
    `<div class="hm-cell hm-${a.BCA}">${SIGNALS[a.BCA]}</div>`,
  ].join('')).join('');
  hm.innerHTML = hdrs + rows;
}

/* ─────────────────────────────────────────
   HISTORY LINE CHART
───────────────────────────────────────── */
function buildHistoryChart(history, assets) {
  if (histChart) histChart.destroy();
  if (!history || history.length === 0) {
    document.getElementById('historyChart').closest('.chart-card').style.display = 'none';
    return;
  }

  const labels  = history.map(h => h.month);
  const palette = [
    '#6c8ff5','#38c8a8','#f59e42','#f87171','#a78bfa',
    '#22c55e','#fb923c','#38bdf8','#e879f9','#facc15',
    '#4ade80','#f472b6','#818cf8','#34d399','#fbbf24',
  ];

  // Build one dataset per asset using consensus score
  const assetIds = [...new Set(assets.map(a => a.id))];
  const datasets = assetIds.map((id, i) => {
    const assetMeta = assets.find(a => a.id === id);
    const data = history.map(h => {
      const row = (h.assets || []).find(a => a.id === id);
      if (!row) return null;
      const avg = ([row.NDR, row.BlackRock, row.BCA].map(s => SCORE[s]||0).reduce((a,b)=>a+b,0)) / 3;
      return Math.round(avg * 100) / 100;
    });
    return {
      label: assetMeta?.name || id,
      data,
      borderColor: palette[i % palette.length],
      backgroundColor: 'transparent',
      borderWidth: 1.5,
      pointRadius: 3,
      tension: 0.3,
    };
  });

  histChart = new Chart(document.getElementById('historyChart'), {
    type: 'line',
    data: { labels, datasets },
    options: {
      responsive: true, maintainAspectRatio: false,
      plugins: { legend: { display: false } },
      scales: {
        x: { grid:{ color:'#252a3a' }, ticks:{ color:'#8892aa', font:{size:10} } },
        y: {
          min: -2, max: 2,
          grid:{ color:'#252a3a' },
          ticks:{ color:'#8892aa', font:{size:10},
            callback: v => ['Heavy UW','UW','Neutral','OW','Heavy OW'][v+2] || v
          }
        }
      }
    }
  });

  // Custom legend
  const legEl = document.getElementById('history-legend');
  legEl.innerHTML = datasets.map(d =>
    `<span style="display:flex;align-items:center;gap:4px;color:var(--c-muted)">
      <span style="width:16px;height:2px;background:${d.borderColor};display:inline-block;border-radius:2px"></span>
      ${d.label}
    </span>`
  ).join('');
}

/* ─────────────────────────────────────────
   BOOT
───────────────────────────────────────── */
document.addEventListener('DOMContentLoaded', boot);
